### ISSUE TITLE
Crashing after a while when using localtunnel

### ISSUE THREAD

**Issue by naholyr** [byteclubfr/copycast#30]
When using `copycast -l`, after some time (26 minutes in my case) the process crashes with following stack:

```
[localtunnel] Error: connection refused: localtunnel.me:46882 (check your firewall settings)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:46882 (check your firewall settings)
    at Socket.<anonymous> (/home/nchambrier/.nvm/versions/node/v6.7.0/lib/node_modules/copycast/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by naholyr** [comment]
I suggest removing all that shit, closed for #36
